Added Keenetic OS detection support
Added bash self-restart for support EACH unix-like environment via posix shebang /bin/sh
Added Keenetic OS detection support

diff --git a/unifetch b/unifetch
--- a/unifetch
+++ b/unifetch
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # vim: noai:ts=4:sw=4:expandtab
 # shellcheck source=/dev/null
 # shellcheck disable=2009 disable=2153 disable=2154 disable=2243 disable=2244
@@ -28,6 +28,18 @@
 # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
+
+# Bash self-restart for support EACH unix-like environment via posix shebang /bin/sh
+if ! ( eval 'a=(1)' ) 2>/dev/null; then
+    if command -v bash >/dev/null 2>&1; then
+        exec bash "$0" "$@"
+    elif command -v osh >/dev/null 2>&1; then
+        exec osh "$0" "$@"
+    else
+        echo "Error: bash-compatible shell was not found!" >&2
+        exit 1
+    fi
+fi
 
 version=1.3.3
 nf_version=7.4.3.3
@@ -1189,6 +1201,18 @@ get_distro() {
                 distro="Synology DSM ${productversion}-${buildnumber} Update ${smallfixnumber}"
 
             else
+               if [ -f /bin/ndmc ]; then
+                    if [ -z "$__NDM_OUT_VER" ]; then
+                        __NDM_OUT_VER=$(/bin/ndmc -c "show version" 2>/dev/null )
+                    fi
+                    if [ ! -z "$__NDM_OUT_VER" ]; then
+                        n_ven=$( echo "$__NDM_OUT_VER" | awk -F': ' '/vendor/ {print $2}' )
+                        n_ver=$( echo "$__NDM_OUT_VER" | awk -F': ' '/title/ {print $2}' )
+                        distro="$n_ven OS $n_ver"
+                        break
+                    fi
+                fi
+
                 for release_file in /etc/*-release; do
                     distro+=$(< "$release_file")
                 done
@@ -1403,6 +1427,16 @@ get_model() {
 
             elif [[ -f /tmp/sysinfo/model ]]; then
                 model=$(< /tmp/sysinfo/model)
+
+            elif [ -f /bin/ndmc ]; then
+                if [ -z "$__NDM_OUT_VER" ]; then
+                    __NDM_OUT_VER=$(/bin/ndmc -c "show version" 2>/dev/null )
+                fi
+                if [ ! -z "$__NDM_OUT_VER" ]; then
+                    n_ven=$( echo "$__NDM_OUT_VER" | awk -F': ' '/vendor/ {print $2}' )
+                    n_mod=$( echo "$__NDM_OUT_VER" | awk -F': ' '/model/ {print $2}' )
+                    model="$n_ven $n_mod"
+                fi
             fi
         ;;
 
@@ -4878,6 +4912,8 @@ print_ascii() {
     ascii_data="${ascii_data//\$\{c4\}/$c4}"
     ascii_data="${ascii_data//\$\{c5\}/$c5}"
     ascii_data="${ascii_data//\$\{c6\}/$c6}"
+    ascii_data="${ascii_data//\$\{bw\}/$( printf '\e[47m' )}"
+    ascii_data="${ascii_data//\$\{rs\}/$( printf '\e[0m' )}"
 
     ((text_padding=ascii_len+gap))
     printf '%b\n' "$ascii_data${reset}"
@@ -11483,6 +11519,26 @@ ${c1}   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
    ██   ██▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██
    ██   ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀██
    ██                       ██
+   ███████████████████████████
+EOF
+        ;;
+
+        "Keenetic OS"*)
+            set_colors 4 7 3
+            read -rd '' ascii_data <<'EOF'
+${c1}   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
+   ███████████████████████████
+   ███████████████████████████
+   ${bw}███    ██████████▀    ▄████${rs}${c1}
+   ${bw}███    ████████▀    ▄██████${rs}${c1}
+   ${bw}███    ██████▀    ▄████████${rs}${c1}
+   ${bw}███              ▀▀████████${rs}${c1}
+   ${bw}███                  ▀█████${rs}${c1}
+   ${bw}███    █████████▄▄▄    ████${rs}${c1}
+   ${bw}███    █████████████    ███${rs}${c1}
+   ${bw}███    █████████████    ███${rs}${c1}
+   ███████████████████████████
+   ███████████████████████████
    ███████████████████████████
 EOF
         ;;
